import './AiGames.css'

function AiGames() {
  return (
    <div className="homeContainer">
      <p className="title">AI generated games</p>
      <p> This is a collection of simple games generated by AI. </p>
      <p>
        {' '}
        I've used{' '}
        <a href="https://beta.openai.com/codex-javascript-sandbox">
          Codex JavaScript
        </a>{' '}
        by OpenAI for this experiment.{' '}
      </p>

      <p className="title">Games:</p>
      <nav>
        <ul>
          <li>
            <a href="/games/tictactoe/index.html">Tic Tac Toe</a>
          </li>
          <li>
            <a href="/games/bullsandcows/index.html">Bulls & Cows</a>
          </li>
        </ul>
      </nav>
    </div>
  )
}

export default AiGames
